name: Communiques vaccin

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  stats-updater:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch communiques
      id: communiques
      run:  python update-communiques.py
      
    - name: Commit communiques
      id: commit
      continue-on-error: true
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add daily_stats.txt
        git commit -m "New communiques"
        
    - name: Push stats
      if: steps.commit.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    - name: Slack notification
      if: steps.commit.outcome == 'success'
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.TEST_SLACK_WEBHOOK_URL }}
      with:
        text: "Nouveaux communiqués!: \n"${{ steps.communiques.outputs.communiques }}""
