# This is a basic workflow to help you get started with Actions

name: Test Slack

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,repo
          custom_payload: |
            {
              attachments: [{
                text: "Testtt",
                "image_url": "https://raw.githubusercontent.com/mlefebvre/updates-vaccination/main/screenshot.png",
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
