name: Texte des rendez-vous

on:
  schedule:
    - cron: "*/15 00,05,06,07,08,20,21,22,23 * * *"
  workflow_dispatch:

jobs:
  stats-updater:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch text
      id: text
      run:  python update-rendez-vous.py
      
    - name: Commit text
      id: commit
      continue-on-error: true
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add texte-rendez-vous.txt
        git commit -m "New rendez-vous text"
        
    - name: Push stats
      if: steps.commit.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    - name: Slack notification
      if: steps.commit.outcome == 'success'
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.TEST_SLACK_WEBHOOK_URL }}
      with:
        text: Le texte des rendez-vous a changé! https://github.com/mlefebvre/covid-actions/blob/main/texte-rendez-vous.txt
