name: Vaccin monitor

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Screenshot Website
        id: screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://portal3.clicsante.ca/covid-vaccination-ouverture
          delay: 2
          full-page: true

      - name: Identify previous screenshot
        uses: mlefebvre/ImageMagick-action@v1.1
        id: screenshot1identify
        with:
          command: identify -quiet -format "%#" screenshot.png

      - name: Copy screenshot
        run: cp ${{ steps.screenshot.outputs.path }} screenshot.png
        
      - name: Crop screenshot
        uses: mlefebvre/ImageMagick-action@v1.1
        with:
          command: convert screenshot.png -crop +0+800 -crop -0-650 screenshot.png
        
      - name: Identify new screenshot
        uses: mlefebvre/ImageMagick-action@v1.1
        id: screenshot2identify
        with:
          command: identify -quiet -format "%#" screenshot.png

      - name: Echo comparison
        run: echo ${{ steps.screenshot1identify.outputs.output }}, ${{ steps.screenshot2identify.outputs.output }}

      - name: Commit screnshot
        id: commit
        if: steps.screenshot1identify.outputs.output != steps.screenshot2identify.outputs.output
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add screenshot.png
          git commit -m "New screenshot"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.screenshot1identify.outputs.output != steps.screenshot2identify.outputs.output
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: 8398a7/action-slack@v3
        if: steps.screenshot1identify.outputs.output != steps.screenshot2identify.outputs.output
        with:
          status: custom
          fields: commit,repo
          custom_payload: |
            {
              attachments: [{
                text: "Y'a eu un update!",
                "image_url": "https://raw.githubusercontent.com/mlefebvre/updates-vaccination/main/screenshot.png",
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
